
package Vista;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Login_dueno;
import modelo.DAO.Login_dueno_DAO;

/**
 *
 * @author _pant
 */
public class Login_dueno_vista extends javax.swing.JFrame {

    /**
     * Creates new form Login_dueno_vista
     */
    
    //trae las clases necesarias
    Login_dueno clase_login_dueno = new Login_dueno();
    Login_dueno_DAO loginduenodao = new Login_dueno_DAO(); 
    
    public Login_dueno_vista() {
        initComponents();
        //imagen para para el escritotio
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo_passarinho_actualizado.png")));
        //centra ventana
        this.setLocationRelativeTo(null);
         /*dimensionar icono de inicio*/
         ImageIcon icono_pasa = new ImageIcon("src/img/logo_passarinho.png"); 
         Icon icono1 = new ImageIcon(icono_pasa.getImage().getScaledInstance(icono_principal.getWidth(),
                 icono_principal.getHeight(), Image.SCALE_DEFAULT));
         icono_principal.setIcon(icono1);
         this.repaint();
    }
    
    public void LimpiarCamposLogin() {
        textfieldcorreo.setText("");
        textfieldclave.setText("");
    }

    public void validar_inicio() {
        
        String correo = textfieldcorreo.getText();
        String clave = String.valueOf(textfieldclave.getPassword());
        
        if (!"".equals(correo) || !"".equals(clave)) {
            clase_login_dueno = loginduenodao.logi(correo, clave);
            if (clase_login_dueno.getCorreo() != null && clase_login_dueno.getClave() != null) {
                LimpiarCamposLogin();
                Admindueno ad = new Admindueno(clase_login_dueno);
                ad.setVisible(true);
                //dispose(); /*cierra el programa*/

            } else {
                JOptionPane.showMessageDialog(null, "correo o contraseñas invalidas");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Los campos no tienen datos");
        }
        
    }
         //funciones de listar
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        icono_principal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textfieldcorreo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        textfieldclave = new javax.swing.JPasswordField();
        button_iniciar_dueno = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setAutoscrolls(true);
        jPanel2.setMinimumSize(new java.awt.Dimension(1366, 710));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel2KeyPressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icono_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_passarinho1.png"))); // NOI18N
        jPanel2.add(icono_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 420, 210));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Inicio de sesión");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Correo");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        textfieldcorreo.setBackground(new java.awt.Color(255, 255, 255));
        textfieldcorreo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textfieldcorreo.setForeground(new java.awt.Color(51, 51, 51));
        textfieldcorreo.setBorder(null);
        textfieldcorreo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        textfieldcorreo.setSelectedTextColor(new java.awt.Color(51, 204, 255));
        textfieldcorreo.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(textfieldcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 410, 35));

        jSeparator1.setBackground(new java.awt.Color(229, 41, 120));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 410, 10));

        jSeparator2.setBackground(new java.awt.Color(229, 41, 120));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 410, 10));

        textfieldclave.setBackground(new java.awt.Color(255, 255, 255));
        textfieldclave.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textfieldclave.setForeground(new java.awt.Color(51, 51, 51));
        textfieldclave.setBorder(null);
        textfieldclave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textfieldclaveKeyPressed(evt);
            }
        });
        jPanel2.add(textfieldclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 410, 35));

        button_iniciar_dueno.setBackground(new java.awt.Color(65, 53, 87));
        button_iniciar_dueno.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(229, 41, 120)));
        button_iniciar_dueno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_iniciar_dueno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_iniciar_duenoMouseClicked(evt);
            }
        });
        button_iniciar_dueno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                button_iniciar_duenoKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Iniciar");

        javax.swing.GroupLayout button_iniciar_duenoLayout = new javax.swing.GroupLayout(button_iniciar_dueno);
        button_iniciar_dueno.setLayout(button_iniciar_duenoLayout);
        button_iniciar_duenoLayout.setHorizontalGroup(
            button_iniciar_duenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, button_iniciar_duenoLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(41, 41, 41))
        );
        button_iniciar_duenoLayout.setVerticalGroup(
            button_iniciar_duenoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(button_iniciar_duenoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(button_iniciar_dueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 130, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Contraseña");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Incio de sesión solo para administradores ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_iniciar_duenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_iniciar_duenoMouseClicked
        validar_inicio();
           //funciones de listar
    
    }//GEN-LAST:event_button_iniciar_duenoMouseClicked

    private void button_iniciar_duenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_button_iniciar_duenoKeyPressed
   
    }//GEN-LAST:event_button_iniciar_duenoKeyPressed

    private void jPanel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel2KeyPressed
      
    }//GEN-LAST:event_jPanel2KeyPressed

    private void textfieldclaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldclaveKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            validar_inicio();
        }  
    }//GEN-LAST:event_textfieldclaveKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_dueno_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_dueno_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_dueno_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_dueno_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_dueno_vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel button_iniciar_dueno;
    private javax.swing.JLabel icono_principal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField textfieldclave;
    private javax.swing.JTextField textfieldcorreo;
    // End of variables declaration//GEN-END:variables
}
