
package Vista;

import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.DAO.LoginDAO;
import modelo.login;

/**
 *
 * @author _pant
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    login lg = new login();
    LoginDAO logindao = new LoginDAO();
    public Login() {
        initComponents();
        /*centrar la ventana*/
         this.setLocationRelativeTo(null);
         /*cerrar ventana a la vez*/
         setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         /*tener un icono en la parte inferior*/
         setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/logo_passarinho_actualizado.png")));
         /*dimensionar foto de inicio*/
         //ImageIcon wallpaper = new ImageIcon("src/img/foto_inicio_sesion_3.jpg"); 
         //Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(foto_inicio_sesion.getWidth(),
                // foto_inicio_sesion.getHeight(), Image.SCALE_DEFAULT));
         //foto_inicio_sesion.setIcon(icono);
       
         
        
         
    }
    
    public void validar_inicio(){
    
        String correo = textfieldcorreo.getText();
        String clave = String.valueOf(textfieldclave.getPassword());
        
        if(!"".equals(correo) || !"".equals(clave)){
               lg = logindao.log(correo, clave);
                        if (lg.getCorreo() != null && lg.getPass() != null) {
                Sistema sis = new Sistema(lg);
                sis.setVisible(true);
                //dispose(); /*cierra el programa*/
              
            }else{
                JOptionPane.showMessageDialog(null, "correo o contraseñas invalidas");
            }
        }else{
             JOptionPane.showMessageDialog(null, "Los campos no tienen datos");
        }
        
        
    }
    
    public void LimpiarCamosLogiPrincipal() {
        textfieldcorreo.setText("");
        textfieldclave.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textfieldcorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        textfieldclave = new javax.swing.JPasswordField();
        Buttoniniciar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        img_datos_agencia = new javax.swing.JLabel();
        icono_principal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(6);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 710));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Inicio de sesión");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 270, 60));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Correo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        textfieldcorreo.setBackground(new java.awt.Color(255, 255, 255));
        textfieldcorreo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textfieldcorreo.setForeground(new java.awt.Color(51, 51, 51));
        textfieldcorreo.setBorder(null);
        textfieldcorreo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        textfieldcorreo.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        textfieldcorreo.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(textfieldcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 410, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(229, 41, 120));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 410, 10));

        jSeparator2.setBackground(new java.awt.Color(229, 41, 120));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 410, 10));

        textfieldclave.setBackground(new java.awt.Color(255, 255, 255));
        textfieldclave.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textfieldclave.setForeground(new java.awt.Color(51, 51, 51));
        textfieldclave.setBorder(null);
        textfieldclave.setSelectedTextColor(new java.awt.Color(102, 102, 102));
        textfieldclave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textfieldclaveKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldclaveKeyTyped(evt);
            }
        });
        jPanel1.add(textfieldclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 410, 35));

        Buttoniniciar.setBackground(new java.awt.Color(65, 53, 87));
        Buttoniniciar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(229, 41, 120)));
        Buttoniniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buttoniniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtoniniciarMouseClicked(evt);
            }
        });
        Buttoniniciar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ButtoniniciarKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Iniciar");

        javax.swing.GroupLayout ButtoniniciarLayout = new javax.swing.GroupLayout(Buttoniniciar);
        Buttoniniciar.setLayout(ButtoniniciarLayout);
        ButtoniniciarLayout.setHorizontalGroup(
            ButtoniniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtoniniciarLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(41, 41, 41))
        );
        ButtoniniciarLayout.setVerticalGroup(
            ButtoniniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtoniniciarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(Buttoniniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 130, -1));

        img_datos_agencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/datos_agencia.png"))); // NOI18N
        img_datos_agencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        img_datos_agencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_datos_agenciaMouseClicked(evt);
            }
        });
        jPanel1.add(img_datos_agencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 30, 40));

        icono_principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_passarinho.png"))); // NOI18N
        jPanel1.add(icono_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-420, 0, 2020, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtoniniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtoniniciarMouseClicked
        validar_inicio();
        LimpiarCamosLogiPrincipal();
    }//GEN-LAST:event_ButtoniniciarMouseClicked

    private void ButtoniniciarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ButtoniniciarKeyPressed
   
    }//GEN-LAST:event_ButtoniniciarKeyPressed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
  
       
    }//GEN-LAST:event_jPanel1KeyPressed

    private void img_datos_agenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_datos_agenciaMouseClicked
        Login_dueno_vista ld = new Login_dueno_vista();
        ld.setVisible(true);
    }//GEN-LAST:event_img_datos_agenciaMouseClicked

    private void textfieldclaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldclaveKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            validar_inicio();
            LimpiarCamosLogiPrincipal();
        }
    }//GEN-LAST:event_textfieldclaveKeyPressed

    private void textfieldclaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldclaveKeyTyped
         
    }//GEN-LAST:event_textfieldclaveKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Buttoniniciar;
    private javax.swing.JLabel icono_principal;
    private javax.swing.JLabel img_datos_agencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField textfieldclave;
    private javax.swing.JTextField textfieldcorreo;
    // End of variables declaration//GEN-END:variables
}
